services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
