spring:
  application:
    name: backend

  datasource:
    url:      jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:tasks}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
