name: CI/CD Pipeline
on:
  push:
    branches:
      - master

# still used by your steps
env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB:     ${{ secrets.DB_NAME }}
          POSTGRES_USER:   ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U $DB_USER -d $DB_NAME; do
            sleep 5
          done

      - name: Build & run tests
        run: mvn clean verify

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/task-backend:${{ github.sha }} \
            -f backend/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-backend:${{ github.sha }}

      - name: Build & push frontend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/task-frontend:${{ github.sha }} \
            -f frontend/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-frontend:${{ github.sha }}
